# Generated by Django 3.1 on 2020-08-26 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(choices=[('Transport z magazynu', 'Transport z magazynu'), ('Odbiór własny', 'Odbiór własny'), ('Kurier', 'Kurier'), ('FoodPost', 'FoodPost'), ('Poprzez przedstawiciela', 'Poprzez przedstawiciela')], max_length=32, verbose_name='Sposób dostawy:')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=8, unique=True, verbose_name='Lokalizacja (xx.xx.xx):')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nazwa produktu:')),
                ('code', models.CharField(max_length=6, unique=True, validators=[wms.models.length_validation], verbose_name='Kod produktu (6 cyfr):')),
                ('description', models.CharField(max_length=64, null=True, verbose_name='Opis produktu:')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena jednostkowa [PLN]:')),
                ('date_to_use', models.DateField(null=True, validators=[wms.models.date_validation], verbose_name='Data przydatności:')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=16, verbose_name='Strefa: ')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(verbose_name='Ilość:')),
                ('localization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.location', verbose_name='Lokalizacja:')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product', verbose_name='Produkt:')),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Ilość')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.product', verbose_name='Produkt:')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms.zone', verbose_name='Strefa:'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(through='wms.OrderList', to='wms.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
